name: Validate repos.json

on:
  push:
    branches:
      - master
    paths:
      - 'public/repos.json'
  pull_request:
    branches:
      - master
    paths:
      - 'public/repos.json'

jobs:
  validate-repos:
    name: Validate repos.json
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@master
      - name: Validate repos.json
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /public/repos_schema.json
          INPUT_JSONS: /public/repos.json
